include:
  - remote: 'https://raw.githubusercontent.com/MAD-I-T/gitlab-ci-magento/v3.32/.magento-actions-full-template.yml'


build:stage:
  extends: .build:stage

security-scan-files:
  extends: .security-scan-files:stage:test

security-scan-module:
  extends: .security-scan-module:stage:test
